apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mass
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    app: nginx
spec:
  nodeSelector:                               
    topology.kubernetes.io/zone: ap-south-1a

#in ebs dynamic provisioning , mentionig selecter node az is not important , pod create ಆದ್ಮೇಲೆ ಅದುನ್ನ ನೋಡ್ಕೊಂಡು 
# ebs volume pod  create  ಆಗಿದ್ az  ಅಲ್ಲೇ ಇದು create ಆಗುತ್ತೆ. why in storage class we mentioned [wait for first consumer] 
# BUT WHAT IF THAT OLD POD GETS DELETED AND NEW POD CREATES IN SOME OTHER NODE ? THEN NODE SELECTOR HELPS 
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-volume
      persistentVolumeClaim:
        claimName: nginx-pvc1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service1
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
