apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Ist-cluster
  region: ap-south-1

managedNodeGroups:
  - name: expense
    instanceType: t2.micro
    desiredCapacity: 3
    spot: true
