apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: expense
spec:
  containers:
  - name: frontend
    image: nginx     # docker run -d --name frontend nginx
    resources:
          requests:
            memory: "64Mi"  #soft limit 64 megabytes
            cpu: "250m"
          limits:
            memory: "128Mi" #hard limit 128 megabytes max.
            cpu: "500m"