apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: expense
  labels:
      project: expense
      environment: dev
spec:
  containers:
  - name: frontend
    image: nginx     # docker run -d --name frontend nginx
