kind: Secret
apiVersion: v1
metadata:
  name: db-secret
type: Opaque    # Opaque is the default type which means not specified under any category
data:
  password: cmFndTEwaW5kaWFuCg==  # base64 encoded password: raghu10indian [ echo 'raghu10indian' | base64 ]
  username: cmFnaHUK


# other types of secret type are:

# Opaque -                              Default type, allows any key-value data.
# kubernetes.io/service-account-token - used to store service account token
# kubernetes.io/dockercfg             - used to store docker config file
# kubernetes.io/dockerconfigjson     - used to store docker config json file
# kubernetes.io/basic-auth
# kubernetes.io/ssh-auth
# kubernetes.io/tls
# kubernetes.io/rsa
# kubernetes.io/rsa-public
# kubernetes.io/ssh-public


#To use secret in a pod: same as Configmap

# apiVersion: v1
# kind: Pod
# metadata:
#   name: backend
# spec:
#   containers:
#   - name: app
#     image: myapp:latest
#     envFrom:
#     - secretRef:
#         name: db-secret



