apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: db              # This is the label of the replicaset. This is used to identify the replicaset only.
    tier: mysql
spec:
  replicas: 3               # Number of pods to be created
  selector:
    matchLabels:
      tier: mysql        # This should be the label of the pod to which this replicaset will manage
  template:
    metadata:
      labels:
        tier: mysql      # (This is the label of the pod) this label should be same as matchLabels of selector  
    spec:
      containers:
      - name: db
        image: rohanraghu/mysql:v1
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  selector:
    tier: mysql     # This is the label of the pod to which this service will route the traffic
  ports:
  - name: mysql-service
    port: 80          # Service Port , this is for other containers to communicate with nginx container
    targetPort: 80    # Container Port
    protocol: TCP
