apiVersion: v1
kind: Pod
metadata:
  name: nginx-almalinux # "_" is not allowed in the name
  namespace: expense
spec:
  containers:
   -  name: logs
      image: almalinux:9
      command: ["sleep", "1000"]